apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-proxysql-configmap
data:
    proxysql.cnf : |
      datadir="/var/lib/proxysql"
      mysql_variables=
      {
          threads={{.Values.proxysql.threads}}
          max_connections={{.Values.proxysql.max_connections}}
          default_query_delay={{.Values.proxysql.default_query_delay}}
          default_query_timeout={{.Values.proxysql.default_query_timeout}}
          have_compress={{.Values.proxysql.have_compress}}
          poll_timeout={{.Values.proxysql.poll_timeout}}
          interfaces="{{.Values.proxysql.interfaces}}"
          default_schema="{{.Values.proxysql.default_schema}}"
          stacksize={{.Values.proxysql.stacksize}}
          server_version="{{.Values.proxysql.server_version}}"
          connect_timeout_server={{.Values.proxysql.connect_timeout_server}}
          monitor_history={{.Values.proxysql.monitor_history}}
          monitor_connect_interval={{.Values.proxysql.monitor_connect_interval}}
          monitor_ping_interval={{.Values.proxysql.monitor_ping_interval}}
          ping_interval_server_msec={{.Values.proxysql.ping_interval_server_msec}}
          ping_timeout_server={{.Values.proxysql.ping_timeout_server}}
          commands_stats={{.Values.proxysql.commands_stats}}
          sessions_sort={{.Values.proxysql.sessions_sort}}
          monitor_username="{{.Values.proxysql.monitor_username}}"
          monitor_password="{{.Values.proxysql.monitor_password}}"
      }
      mysql_replication_hostgroups =
      (
              { writer_hostgroup=10, reader_hostgroup=20, comment="MySQL Replication 5.7", check_type="{{.Values.proxysql.check_type}}" }
      )
      mysql_servers =
      (
               {{ range .Values.mysql.readers }}
               { address="{{.endpoint}}" , port={{.port}} , hostgroup=20, max_connections={{.max_connections}} },
               {{ end }}
               { address="{{.Values.mysql.writer.endpoint}}" , port={{.Values.mysql.writer.port}} , hostgroup=10, max_connections={{.Values.mysql.writer.max_connections}} }
      )
      mysql_users =
      (
              { username = "{{.Values.mysql.username}}" , password = "{{.Values.mysql.password}}"  , active = 1 }
      )
      mysql_query_rules =
      (
          {
                  rule_id=100
                  active=1
                  match_pattern="^SELECT .* FOR UPDATE"
                  destination_hostgroup=10
                  apply=1
          },
          {
                  rule_id=200
                  active=1
                  match_pattern="^SELECT .*"
                  destination_hostgroup=20
                  apply=1
          },
          {
                  rule_id=300
                  active=1
                  match_pattern=".*"
                  destination_hostgroup=10
                  apply=1
          }
      )